name: Bubble
on:
  # starts on every push on main branch !
  push:
    branches: [ "main" ]

  # starts automatically every 5 hour !
  schedule:
    - cron: '0 */5 * * *'

  # enable manual startup !
  workflow_dispatch:

# checks if there's any host already running and kills it !
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
      SPOTID: ${{secrets.SPOTID }}
      SPOTSEC: ${{secrets.SPOTSEC }}
      GIT: ${{secrets.GIT}}
      GLSEARCH: ${{secrets.GLSEARCH}}
      REPO: ${{ github.repository }}
    steps:
      - name: checkout the source.
        uses: actions/checkout@v2

      - name: Update APT package lists
        run: sudo apt-get update

      - name: Fix missing packages
        run: sudo apt-get update --fix-missing -y

      - name: Install ffmpeg and ffprobe
        run: sudo apt install ffmpeg -y

      - name: install requirements
        run: pip install -r requirements.txt

      - name: starting bubble.
        run: python3 src/main.py
