name: CI
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{secrets.TOKEN}}
      SPOTID: ${{secrets.SPOTID }}
      SPOTSEC: ${{secrets.SPOTSEC }}
      GIT: ${{secrets.GIT}}
      GLSEARCH: ${{secrets.GLSEARCH}}
      REPO: ${{ github.repository }}
    steps:
      - name: GIT clone the main repo !
        run: |
          rm -rf /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          cd /home/runner/work/${{ github.event.repository.name }}
          git clone https://github.com/${{ github.repository }}.git
      - name: Run a multi-line script
        run: |
          BOTDIR="/home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}"
          cd $BOTDIR
          bash $BOTDIR/main.sh
